# Site settings
title: Xiakai's Blog
SEOTitle: 夏凯的博客 | Xiakai's Blog     #浏览器搜索及加载时的标题
header-img: img/post-bg-desk.jpg        #首页背景图片
email: 13212017962@163.com
description: "Nothing is everything, everything is nothing."    #网站介绍
keyword: "Xiakai, Xiakai's Blog, 夏凯的博客, PanXiakai, 潘夏凯, CS, fundamental"
url: "http://panxiakai.github.io"          # your host, for absolute URL
baseurl: "https://PanXiakai.github.io"      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/PanXiakai/Panxiakai.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Go ahead with goals, have a rest with goals, I go!"
sidebar-avatar: /img/avatar_m.jpg      # personal img; use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:     风尘
github_username:    PanXaikai
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
# Gittalk cannot be setted correctly.
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 8d3e7ca579a789e74e13                            #生成的clientID
  clientSecret: b90a32b6dcc9762969e4c0ce405f5d352f54b3e1    #生成的clientSecret
  repo: panxiakai.github.io    #仓库名称
  owner: PanXiakai    #github用户名
  admin: PanXiakai
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#    {
#        title: "WY",
#        href: "http://zhengwuyang.com"
#    },{
#        title: "简书·BY",
#        href: "http://www.jianshu.com/u/e71990ada2fd"
#    },{
#        title: "Apple",
#        href: "https://apple.com"
#    },{
#        title: "Apple Developer",
#        href: "https://developer.apple.com/"
#    }
#]

theme: jekyll-theme-architect